# Generated by Django 4.2.7 on 2025-03-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_disbursement_date_remove_loan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid')], default='ACTIVE', max_length=20),
        ),
    ]
